defmodule TitanFlowWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :titan_flow

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_titan_flow_key",
    signing_salt: "JeCm+jDI",
    encryption_salt: "i/6kx1pc5IBLbZylMrmIEGANRg8ikrdzdR9bTkAy5bU=",
    same_site: "Strict",
    secure: Application.compile_env(:titan_flow, :secure_cookies, true)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :titan_flow,
    gzip: not code_reloading?,
    only: TitanFlowWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :titan_flow
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {TitanFlowWeb.Endpoint, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TitanFlowWeb.Router

  def read_body(conn, opts) do
    case Plug.Conn.read_body(conn, opts) do
      {:ok, body, conn} ->
        {:ok, body, maybe_put_raw_body(conn, body)}

      {:more, body, conn} ->
        {:more, body, maybe_put_raw_body(conn, body)}

      {:error, _} = error ->
        error
    end
  end

  defp put_raw_body(conn, body) do
    existing = conn.assigns[:raw_body] || ""
    Plug.Conn.assign(conn, :raw_body, existing <> body)
  end

  defp maybe_put_raw_body(conn, body) do
    if conn.request_path == "/api/webhooks" or
         String.starts_with?(conn.request_path, "/api/webhooks/") do
      put_raw_body(conn, body)
    else
      conn
    end
  end
end
