import Config

# Configure your database
config :titan_flow, TitanFlow.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "titan_flow_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  prepare: :unnamed,  # Supavisor Transaction Mode compatible
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :titan_flow, TitanFlowWeb.Endpoint,
  # Binding to all interfaces to allow external access
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ITUL6tMPdrhHN3vdWXebNksvhx4psHg4m3YmUWJHhqRuWyDPmKrm5bTu1qFrm1k8",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:titan_flow, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:titan_flow, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :titan_flow, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
